name: build-and-test
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
          python-version: [3.6]
    steps:
      - uses: actions/checkout@v2

      - name: Install Flake
        run: |
          python -m pip install flake8

      - name: Run Flake
        run: python flake8 ccnmtlsettings
